import = ["/home/simon/.config/alacritty/themes/catppuccin-mocha.toml"]

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Meslo LGS Nerd Font"
# style = "bold"

[window]
decorations = "buttonless"
opacity = 1.0

[window.padding]
x = 10
y = 10
